/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'huj' at '2/18/16 9:58 AM' with Gradle 2.9
 *
 * @author huj, @date 2/18/16 9:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
